# Generated by Django 4.2.9 on 2025-04-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Телефон"),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "medical_insurance_number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Номер полиса ОМС"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Аллергии"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(verbose_name="Запланированное время"),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактическое время начала"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Фактическое время окончания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Запланирована"),
                            ("IN_PROGRESS", "В процессе"),
                            ("COMPLETED", "Завершена"),
                            ("CANCELED", "Отменена"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("complaint", models.TextField(verbose_name="Жалоба")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Заключение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_telemedicine_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_sessions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телемедицинская консультация",
                "verbose_name_plural": "Телемедицинские консультации",
                "ordering": ["-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=255, verbose_name="Диагноз")),
                ("symptoms", models.TextField(verbose_name="Симптомы")),
                ("treatment", models.TextField(verbose_name="Лечение")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечания"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинская запись",
                "verbose_name_plural": "Медицинские записи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(verbose_name="Дата и время")),
                ("reason", models.TextField(verbose_name="Причина обращения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Запланирован"),
                            ("COMPLETED", "Завершен"),
                            ("CANCELED", "Отменен"),
                            ("RESCHEDULED", "Перенесен"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечания"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прием",
                "verbose_name_plural": "Приемы",
                "ordering": ["-date_time"],
            },
        ),
    ]
